

  - name: configure fedora
    import_tasks: fedora.yml
    when: ansible_distribution|lower == 'fedora'

  - name: configure ubuntu
    import_tasks: ubuntu.yml
    when: ansible_distribution|lower == 'ubuntu'


  - name: configure windows
    import_tasks: windows.yml
    when: ansible_os_family|lower == 'windows'







