


    

# do stuff for Ubuntu

  - name: install basic packages for Ubuntu
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present
    with_items:
      - apache2
      - git
      - php5
      - php5-mysql
      - mysql-server
      - mysql-client-5.5
      - python-mysqldb
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.10"
    become: true

# Ubuntu 17.10 has crazy versions
  - name: install basic packages for Ubuntu
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present
    with_items:
      - apache2
      - git
      - php   # is version 7
      - php-mysql
      - mysql-server
      - mysql-client
      - python-mysqldb
      - openjdk-8-jdk-headless
      - maven
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "17.10"
    become: true

#tolland: you can use 'register: foo' on the 'git' task and 'when: foo|changed' on the 'template' task to only update the template when the git repo is updated (by ansible) 
  - name: install the Much Assembly backend
    git:
      repo: https://github.com/simon987/Much-Assembly-Required.git
      dest: /opt/Much-Assembly-Required
      update: no
    become: true

  - name: install the Much Assembly frontend
    git:
      repo: https://github.com/simon987/Much-Assembly-Required-Frontend.git
      dest: "/var/www/html/{{ mar_web_path }}"
      update: no
    become: true


  - apache2_module:
      state: present
      name: proxy_wstunnel
    become: true
    when: ansible_distribution == 'Ubuntu'
    notify:
    - restart apache2


  - apache2_module:
      state: present
      name: proxy
    become: true
    when: ansible_distribution == 'Ubuntu'
    notify:
    - restart apache2

  - template:
      src: templates/websocket_proxy.j2
      dest: /etc/apache2/conf-enabled/websocket_proxy.conf
      owner: root
      group: root
      mode: 0644
    become: true
    when: ansible_distribution == 'Ubuntu'
    notify:
    - restart apache2

  - template:
      src: templates/config.php.j2
      dest: "/var/www/html/{{ mar_web_path }}include/config.php"
      owner: root
      group: root
      mode: 0644
    become: true
    when: ansible_distribution == 'Ubuntu'
    notify:
    - restart apache2
    


  - service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == 'Ubuntu'
    become: true


  - name: Create a new database with name 'mar'
    mysql_db:
      name: mar
      state: present
    become: true
#    notify:
#    - import data
      
#  - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
#    mysql_db:
#      state: import
#      name: mar
#      target: /var/www/html/Much-Assembly-Required-Frontend/database.sql
#    become: true

#GRANT ALL PRIVILEGES ON mydb.* TO 'myuser'@'%' WITH GRANT OPTION;
  - mysql_user:
      name: mar
      password: mar
      priv: 'mar.*:ALL'
      state: present


#  - template:
#      src: templates/collectd.j2
#      dest: /etc/apache2/conf-enabled/collectd.conf
#      owner: root
#      group: root
#      mode: 0644
#    become: true
#    when: ansible_distribution == 'Ubuntu'
#    notify:
#    - restart apache2
#
#
#  - apache2_module:
#      state: present
#      name: cgid
#    become: true
#    when: ansible_distribution == 'Ubuntu'
#    notify:
#    - restart apache2

# end of ubutu specific stuff ##
    
    