
#
#
#

  - name: install basic packages for Windows
    action: >
      win_chocolatey name={{ item }} state=present
    with_items:
      - jdk8
      - mongodb
      - mysql
      - php
      - maven
      - apache-httpd
    
    

