



  - name: restart apache2
    service: name=apache2 state=restarted
    become: true


  - name: restart much-assembly-required
    service: name=much-assembly-required state=restarted
    become: true

